Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.8/dist-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
load_dir = pjoin(results_dir, '4way')

_ = mk_lda_summary_plot(load_dir, dpi=70)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m<ipython-input-3-98a16cf9c79e>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0mload_dir[0m [0;34m=[0m [0mpjoin[0m[0;34m([0m[0mresults_dir[0m[0;34m,[0m [0;34m'4way'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0;34m[0m[0m
[0;32m----> 3[0;31m [0m_[0m [0;34m=[0m [0mmk_lda_summary_plot[0m[0;34m([0m[0mload_dir[0m[0;34m,[0m [0mdpi[0m[0;34m=[0m[0;36m70[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/Dropbox/git/A1ToneDiscrimination/utils/plot_functions.py[0m in [0;36mmk_lda_summary_plot[0;34m(load_dir, save_file, display, figsize, dpi)[0m
[1;32m     25[0m     [0msummary[0m [0;34m=[0m [0mpd[0m[0;34m.[0m[0mDataFrame[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     26[0m     [0;32mfor[0m [0mdim[0m [0;32min[0m [0;34m[[0m[0;36m1[0m[0;34m,[0m [0;36m2[0m[0;34m,[0m [0;36m3[0m[0;34m][0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 27[0;31m         [0mresults[0m [0;34m=[0m [0mpd[0m[0;34m.[0m[0mread_pickle[0m[0;34m([0m[0mpjoin[0m[0;34m([0m[0mload_dir[0m[0;34m,[0m [0;34m'results_{:d}d.df'[0m[0;34m.[0m[0mformat[0m[0;34m([0m[0mdim[0m[0;34m)[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     28[0m         [0mbest_t[0m [0;34m=[0m [0mresults[0m[0;34m.[0m[0mbest_t_global[0m[0;34m.[0m[0munique[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mitem[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     29[0m [0;34m[0m[0m

[0;32m/usr/local/lib/python3.8/dist-packages/pandas/io/pickle.py[0m in [0;36mread_pickle[0;34m(filepath_or_buffer, compression)[0m
[1;32m    167[0m     [0;32mif[0m [0;32mnot[0m [0misinstance[0m[0;34m([0m[0mfp_or_buf[0m[0;34m,[0m [0mstr[0m[0;34m)[0m [0;32mand[0m [0mcompression[0m [0;34m==[0m [0;34m"infer"[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    168[0m         [0mcompression[0m [0;34m=[0m [0;32mNone[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 169[0;31m     [0mf[0m[0;34m,[0m [0mfh[0m [0;34m=[0m [0mget_handle[0m[0;34m([0m[0mfp_or_buf[0m[0;34m,[0m [0;34m"rb"[0m[0;34m,[0m [0mcompression[0m[0;34m=[0m[0mcompression[0m[0;34m,[0m [0mis_text[0m[0;34m=[0m[0;32mFalse[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    170[0m [0;34m[0m[0m
[1;32m    171[0m     [0;31m# 1) try standard library Pickle[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.8/dist-packages/pandas/io/common.py[0m in [0;36mget_handle[0;34m(path_or_buf, mode, encoding, compression, memory_map, is_text, errors)[0m
[1;32m    497[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    498[0m             [0;31m# Binary mode[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 499[0;31m             [0mf[0m [0;34m=[0m [0mopen[0m[0;34m([0m[0mpath_or_buf[0m[0;34m,[0m [0mmode[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    500[0m         [0mhandles[0m[0;34m.[0m[0mappend[0m[0;34m([0m[0mf[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    501[0m [0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/root/Documents/A1/results/lda/4way/results_1d.df'
FileNotFoundError: [Errno 2] No such file or directory: '/root/Documents/A1/results/lda/4way/results_1d.df'

